[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"


opacity = 0.8

blur = false

#option_as_alt = "Both"

[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "xdg-open"
hyperlinks = false
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

[scrolling]
history = 100000

[font]
size=16

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[general]
import = [
    "/Users/life/.config/alacritty/mellow.toml"
]
